me.game.enemies = {
  //dictionary of all enemies
  snake: {
    min: 0,
    max: 10,
    exp: 20,
    hp: 2,
    damage: 1,
    defense: 0,
    behavior: 'aggressive',
    image: 'snake'
  },
  skeleton: {
    min: 3,
    max: 15,
    exp: 35,
    hp: 4,
    damage: 2,
    defense: 0,
    behavior: 'aggressive',
    image: 'skeleton1'
  },
  skull: {
    min: 5,
    max: 20,
    exp: 35,
    hp: 8,
    damage: 3,
    defense: 2,
    behavior: 'indifferent',
    image: 'skull'
  },
  monk: {
    min: 8,
    max: 25,
    exp: 40,
    hp: 15,
    damage: 4,
    defense: 0,
    behavior: 'aggressive',
    image: 'monk'
  },
  book: {
    min: 10,
    max: 25,
    exp: 40,
    hp: 15,
    damage: 3,
    defense: 2,
    behavior: 'aggressive',
    image: 'book'
  },
  zombie: {
    min: 13,
    max: 30,
    exp: 70,
    hp: 18,
    damage: 3,
    defense: 5,
    behavior: 'scared',
    image: 'zombie'
  },
  coolpuke: {
    min: 20,
    max: 35,
    exp: 40,
    hp: 16,
    damage: 8,
    defense: 5,
    behavior: 'aggressive',
    image: 'coolpuke'
  },
  evilsword: {
    min: 20,
    max: 45,
    exp: 50,
    hp: 18,
    damage: 12,
    defense: 4,
    behavior: 'aggressive',
    image: 'evilsword'
  },
  mrspook: {
    min: 25,
    max: 35,
    exp: 80,
    hp: 35,
    damage: 5,
    defense: 20,
    behavior: 'scared',
    image: 'mrspook'
  },
  eyehole: {
    min: 30,
    max: 50,
    exp: 30,
    hp: 22,
    damage: 12,
    defense: 9,
    behavior: 'indifferent',
    image: 'eyehole'
  },
  skeleton2: {
    min: 30,
    max: 60,
    exp: 40,
    hp: 23,
    damage: 8,
    defense: 11,
    behavior: 'aggressive',
    image: 'skeleton2'
  },
  wtf: {
    min: 15,
    max: 70,
    exp: 80,
    hp: 5,
    damage: 25,
    defense: 20,
    behavior: 'aggressive',
    image: 'wtf'
  },
  her: {
    min: 15,
    max: 35,
    exp: 50,
    hp: 24,
    damage: 8,
    defense: 6,
    behavior: 'aggressive',
    image: 'her',
  },
  wtf2: {
    min: 15,
    max: 40,
    exp: 10,
    hp: 5,
    damage: 2,
    defense: 30,
    behavior: 'aggressive',
    image: 'wtf'
  },
  wtf3: {
    min: 25,
    max: 50,
    exp: 30,
    hp: 15,
    damage: 10,
    defense: 18,
    behavior: 'indifferent',
    image: 'wtf'
  },
  zombie2: {
    min: 35,
    max: 55,
    exp: 45,
    hp: 25,
    damage: 15,
    defense: 22,
    behavior: 'aggressive',
    image: 'zombie2'
  },
  skull2: {
    min: 45,
    max: 65,
    exp: 50,
    hp: 38,
    damage: 20,
    defense: 25,
    behavior: 'aggressive',
    image: 'skull2',
  },
  monk2: {
    min: 45,
    max: 65,
    exp: 70,
    hp: 50,
    damage: 40,
    defense: 30,
    behavior: 'indifferent',
    image: 'monk2'
  },
  coolpuke2: {
    min: 50,
    max: 70,
    exp: 30,
    hp: 45,
    damage: 25,
    defense: 35,
    behavior: 'aggressive',
    image: 'coolpuke2',
  },
  him: {
    min: 55,
    max: 85,
    exp: 48,
    hp: 50,
    damage: 40,
    defense: 35,
    behavior: 'aggressive',
    image: 'him'
  },
  skeleton3: {
    min: 60,
    max: 80,
    exp: 40,
    hp: 65,
    damage: 30,
    defense: 40,
    behavior: 'aggressive',
    image: 'skeleton3',
  },
  book2: {
    min: 65,
    max: 90,
    exp: 70,
    hp: 60,
    damage: 50,
    defense: 60,
    behavior: 'indifferent',
    image: 'book2',
  },
  eyehole2: {
    min: 70,
    max: 100,
    exp: 50,
    hp: 80,
    damage: 40,
    defense: 45,
    behavior: 'aggressive',
    image: 'eyehole2',
  },
  book3: {
    min: 85,
    max: 100,
    exp: 40,
    hp: 100,
    damage: 55,
    defense: 50,
    behavior: 'aggressive',
    image: 'book3',
  },
  evilsword2: {
    min: 90,
    max: 100,
    exp: 60,
    hp: 130,
    damage: 80,
    defense: 60,
    behavior: 'indifferent',
    image: 'evilsword2',
  },
  thing: {
    min: 1,
    max: 100,
    exp: 100,
    hp: 70,
    damage: 70,
    defense: 50,
    behavior: 'indifferent',
    image: 'thing'
  }
};
